services:
  - type: web
    name: shl-recommendation-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: $PORT
      - key: SHL_API_KEY
        sync: false
      - key: SHL_API_BASE_URL
        value: https://api.shl.com/v1 