services:
  - type: web
    name: shl-recommendation-engine
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"
    startCommand: gunicorn main:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --log-level info
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: $PORT
      - key: SHL_API_KEY
        sync: false
      - key: SHL_API_BASE_URL
        value: https://api.shl.com/v1
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 